Implement lazy initialization of pointers in KLEE
staticafi/klee pull request #15
Opened 2022-03-25 22:19 UTC by capsosk

Implement lazy initialization of objects which are passes to entry_point function by arguments and
implement lazy initialization of external pointers.

2022-04-13 17:11 UTC, mchalupa requested changes

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +void Executor::dumpState(std::unique_ptr<llvm::raw_fd_ostream>& os, ExecutionState* es) {
It would be better to have one commit for `CreateArray` and one commit for `dumpState` and explain in the commit message why is that necessary.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/AddressSpace.cpp
> +    if (value->getWidth() != Context::get().getPointerWidth()) {
This is no reformatting nor refactoring, it does not belong to this commit. And it should be documented what this change does (either as as a comment or as a commit message).

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/AddressSpace.h
> +        concreteAddressMap(b.concreteAddressMap),
Again, this is no reformatting/refactoring.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +/* Jakub Novak - lazy init pointers*/
This comment is redundant (we know your name from commits ;)

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +          result = handleReadForLazyInit(state, target, mo, os, offset,shouldReadFromOffset);
A nitpick: missing space before `shouldReadFromOffset`

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +  Expr::Width type = (getWidthForLLVMType(target->inst->getType()));
Nitpick: extra parentheses.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +      (void)bindObjectInState(state, valueMO, isLocal, nullptr);
Why is there the cast to `void`?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +      terminateStateOnError(state, "Couldn't get offset for Lazy Init", Unhandled);
Shouldn't the code return from the function here after terminating the state?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +      terminateStateOnError(state, "segment not found in lazilyInitializedOffsets", Unhandled);
The same here, the code shouldn't probably continue after terminating the state, or should it?

2022-04-13 17:11 UTC, mchalupa commented on test/Feature/LazyInitInt.c
> +// RUN: %clang %s -emit-llvm %O0opt -c -o %t1.bc
It would be nice to have the tests in a new commit.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +                       cl::desc("Initialize external pointers lazily"),
This change should be merged into the commit that introduced '"lazy-init" parameter.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +      result = {pair->second, constantZero};
What should this change do? And how does it relate to max depth?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +
Could you document what this commit does in the commit message? It is hard to find out what you did here...

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +    terminateStateOnError(state, "Couldn't get offset for Lazy Init", Unhandled);
Missing `return`?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +    terminateStateOnError(state, "segment not found in lazilyInitializedOffsets", Unhandled);
Missing `return`?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +    klee_warning("Entry function %s has arguments", f->getName().data());
Why is here the warning?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +    klee_warning("entry function %s has var args", f->getName().data());
Why this warning?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +                            User);
Return?

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +    MemoryObject** varargs = &state.stack.back().varargs;
This would deserve a comment -- here or in the commit message.

2022-04-13 17:11 UTC, mchalupa commented on lib/Core/Executor.cpp
> +        ref<Expr> size = getPointerSymbolicSizeExpr(state);
The name of the commit is misleading, could you rename it e.g., to `extract method for creating/getting symbolic size` or something like that?

2022-04-23 19:19 UTC, capsosk commented on lib/Core/Executor.cpp
> +      (void)bindObjectInState(state, valueMO, isLocal, nullptr);
to ignore the return value

2022-04-25 05:23 UTC, mchalupa commented on lib/Core/Executor.cpp
> +      (void)bindObjectInState(state, valueMO, isLocal, nullptr);
> to ignore the return value

I know what it does, but why is it needed? The value is ignored even without it.

2022-05-07 10:33 UTC, closed without merging